steps:
  # Pull previous image for layer caching
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull gcr.io/gen-lang-client-0521299386/backend-image:latest || exit 0'
  
  # Build with cache
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--cache-from', 'gcr.io/gen-lang-client-0521299386/backend-image:latest',
      '-t', 'gcr.io/gen-lang-client-0521299386/backend-image:latest',
      '-f', 'backend/Dockerfile',
      'backend'
    ]

images:
  - 'gcr.io/gen-lang-client-0521299386/backend-image:latest'