steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', 'gcr.io/gen-lang-client-0521299386/backend-image:latest', '.']
images:
  - 'gcr.io/gen-lang-client-0521299386/backend-image:latest'
