apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: hack-western
build:
  artifacts:
  - image: backend-image
    context: backend
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - deployment/k8s/*.yaml
deploy:
  kubectl: {}
